// Code generated by Kitex v0.15.1. DO NOT EDIT.

package profile

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	userService "github.com/muixstudio/clio/internal/common/pb/userService"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"FindUserProfile": kitex.NewMethodInfo(
		findUserProfileHandler,
		newFindUserProfileArgs,
		newFindUserProfileResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	profileServiceInfo                = NewServiceInfo()
	profileServiceInfoForClient       = NewServiceInfoForClient()
	profileServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return profileServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return profileServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return profileServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Profile"
	handlerType := (*userService.Profile)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "userService",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.1",
		Extra:           extra,
	}
	return svcInfo
}

func findUserProfileHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(userService.FindUserProfileRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(userService.Profile).FindUserProfile(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FindUserProfileArgs:
		success, err := handler.(userService.Profile).FindUserProfile(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FindUserProfileResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFindUserProfileArgs() interface{} {
	return &FindUserProfileArgs{}
}

func newFindUserProfileResult() interface{} {
	return &FindUserProfileResult{}
}

type FindUserProfileArgs struct {
	Req *userService.FindUserProfileRequest
}

func (p *FindUserProfileArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FindUserProfileArgs) Unmarshal(in []byte) error {
	msg := new(userService.FindUserProfileRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FindUserProfileArgs_Req_DEFAULT *userService.FindUserProfileRequest

func (p *FindUserProfileArgs) GetReq() *userService.FindUserProfileRequest {
	if !p.IsSetReq() {
		return FindUserProfileArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FindUserProfileArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FindUserProfileArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FindUserProfileResult struct {
	Success *userService.FindUserProfileResponse
}

var FindUserProfileResult_Success_DEFAULT *userService.FindUserProfileResponse

func (p *FindUserProfileResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FindUserProfileResult) Unmarshal(in []byte) error {
	msg := new(userService.FindUserProfileResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FindUserProfileResult) GetSuccess() *userService.FindUserProfileResponse {
	if !p.IsSetSuccess() {
		return FindUserProfileResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FindUserProfileResult) SetSuccess(x interface{}) {
	p.Success = x.(*userService.FindUserProfileResponse)
}

func (p *FindUserProfileResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FindUserProfileResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) FindUserProfile(ctx context.Context, Req *userService.FindUserProfileRequest) (r *userService.FindUserProfileResponse, err error) {
	var _args FindUserProfileArgs
	_args.Req = Req
	var _result FindUserProfileResult
	if err = p.c.Call(ctx, "FindUserProfile", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
