import {
  AudioWaveform,
  BadgeCheck,
  Bell,
  BookOpen,
  Bot,
  ChartBar,
  ChevronRight,
  ChevronsUpDown,
  Command,
  CreditCard,
  Folder,
  Forward,
  Frame,
  GalleryVerticalEnd,
  Home,
  Inbox,
  LayoutDashboard,
  LogOut,
  Map,
  Moon,
  MoreHorizontal,
  PanelLeft,
  PieChart,
  Plus,
  Search,
  Settings,
  Settings2,
  Shield,
  Sparkles,
  SquareTerminal,
  Sun,
  Trash2,
  Users,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const sidebarIconRegistry: Record<string, LucideIcon> = {
  AudioWaveform,
  BadgeCheck,
  Bell,
  BookOpen,
  Bot,
  ChartBar,
  ChevronRight,
  ChevronsUpDown,
  Command,
  CreditCard,
  Folder,
  Forward,
  Frame,
  GalleryVerticalEnd,
  Home,
  Inbox,
  LayoutDashboard,
  LogOut,
  Map,
  Moon,
  MoreHorizontal,
  PanelLeft,
  PieChart,
  Plus,
  Search,
  Settings,
  Settings2,
  Shield,
  Sparkles,
  SquareTerminal,
  Sun,
  Trash2,
  Users,
};

export function getSidebarIcon(name: string | undefined): LucideIcon | undefined {
  if (!name) return undefined;
  return sidebarIconRegistry[name];
}