// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: proto/profile.proto

package userService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint64                `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserProfileRequest) Reset() {
	*x = FindUserProfileRequest{}
	mi := &file_proto_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserProfileRequest) ProtoMessage() {}

func (x *FindUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserProfileRequest.ProtoReflect.Descriptor instead.
func (*FindUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{0}
}

func (x *FindUserProfileRequest) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

type FindUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserName      string                 `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	CountryCode   string                 `protobuf:"bytes,4,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,7,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserProfileResponse) Reset() {
	*x = FindUserProfileResponse{}
	mi := &file_proto_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserProfileResponse) ProtoMessage() {}

func (x *FindUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserProfileResponse.ProtoReflect.Descriptor instead.
func (*FindUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_proto_rawDescGZIP(), []int{1}
}

func (x *FindUserProfileResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FindUserProfileResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FindUserProfileResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *FindUserProfileResponse) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *FindUserProfileResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *FindUserProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FindUserProfileResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

var File_proto_profile_proto protoreflect.FileDescriptor

const file_proto_profile_proto_rawDesc = "" +
	"\n" +
	"\x13proto/profile.proto\x12\vuserService\"4\n" +
	"\x16FindUserProfileRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x04H\x00R\x02id\x88\x01\x01B\x05\n" +
	"\x03_id\"\xc1\x01\n" +
	"\x17FindUserProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\buserName\x18\x03 \x01(\tR\buserName\x12 \n" +
	"\vcountryCode\x18\x04 \x01(\tR\vcountryCode\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x18\n" +
	"\aisAdmin\x18\a \x01(\bR\aisAdmin2g\n" +
	"\aProfile\x12\\\n" +
	"\x0fFindUserProfile\x12#.userService.FindUserProfileRequest\x1a$.userService.FindUserProfileResponseB\x10Z\x0epb/userServiceb\x06proto3"

var (
	file_proto_profile_proto_rawDescOnce sync.Once
	file_proto_profile_proto_rawDescData []byte
)

func file_proto_profile_proto_rawDescGZIP() []byte {
	file_proto_profile_proto_rawDescOnce.Do(func() {
		file_proto_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_profile_proto_rawDesc), len(file_proto_profile_proto_rawDesc)))
	})
	return file_proto_profile_proto_rawDescData
}

var file_proto_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_profile_proto_goTypes = []any{
	(*FindUserProfileRequest)(nil),  // 0: userService.FindUserProfileRequest
	(*FindUserProfileResponse)(nil), // 1: userService.FindUserProfileResponse
}
var file_proto_profile_proto_depIdxs = []int32{
	0, // 0: userService.Profile.FindUserProfile:input_type -> userService.FindUserProfileRequest
	1, // 1: userService.Profile.FindUserProfile:output_type -> userService.FindUserProfileResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_profile_proto_init() }
func file_proto_profile_proto_init() {
	if File_proto_profile_proto != nil {
		return
	}
	file_proto_profile_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_profile_proto_rawDesc), len(file_proto_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_profile_proto_goTypes,
		DependencyIndexes: file_proto_profile_proto_depIdxs,
		MessageInfos:      file_proto_profile_proto_msgTypes,
	}.Build()
	File_proto_profile_proto = out.File
	file_proto_profile_proto_goTypes = nil
	file_proto_profile_proto_depIdxs = nil
}
