/*
 * Copyright 2026 MuixStudio
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Package oidc implements a generic OAuth2 / OIDC strategy.
//
// File layout:
//
//   - provider.go      — Provider interface + normalized Claims struct
//   - state.go         — CSRF state store (sync.Map + expiry)
//   - strategy.go      — HTTP handlers, find-or-create, session issuance
//   - provider_github.go — GitHub OAuth2 implementation of Provider
//
// Adding a new provider (e.g. Google) means creating provider_google.go
// and implementing the three-method Provider interface. Zero changes to
// strategy.go or the driver are needed.
package oidc

import "context"

// Provider is the interface every OAuth2 / OIDC provider must implement.
// It abstracts away provider-specific URLs, token exchanges, and API calls
// so that strategy.go only ever deals with normalized Claims.
type Provider interface {
	// ID returns the provider's stable slug (e.g. "github", "google").
	// This slug is used in route paths: /self-service/auth/{id}/start
	ID() string

	// AuthCodeURL builds the authorization URL the user must be redirected to.
	// state is a random CSRF token generated by the strategy and verified on
	// callback to prevent CSRF attacks.
	// queryMap carries additional query parameters appended verbatim to the URL
	// (e.g. {"return_to": "https://example.com"} for a post-login redirect hint).
	// Keys in queryMap must not shadow standard OAuth2 parameters such as
	// client_id, redirect_uri, scope, or state.
	AuthCodeURL(state string) string

	// Exchange trades the one-time authorization code for user Claims.
	// All provider-specific HTTP calls (token exchange, user-info fetch)
	// happen here; the strategy never touches raw access tokens.
	Exchange(ctx context.Context, code string) (*Claims, error)
}

// Claims is the normalized set of user attributes returned by any provider.
type Claims struct {
	// Subject is the stable, unique identifier at the provider.
	// For GitHub this is the numeric user ID as a string.
	// It must never be empty.
	Subject string

	// Issuer identifies the provider (e.g. the token endpoint URL).
	Issuer string

	Email    string
	Name     string
	Nickname string // e.g. GitHub login / username
	Picture  string
}
