proto:
	protoc --proto_path=. --micro_out=. --go_out=:. proto/user.proto
	protoc --proto_path=. --micro_out=. --go_out=:. proto/profile.proto
	protoc --proto_path=. --micro_out=. --go_out=:. proto/usergroup.proto
